export const START_RECORDING = "START_RECORDING";
export const STOP_RECORDING = "STOP_RECORDING";
export const CLEAR_RECORDING = "CLEAR_RECORDING";
export const PLAY_RECORDING = "PLAY_RECORDING";
export const STORE_ACTION = "STORE_ACTION";
